import { useEffect,useState } from "react";
import { apiRequest } from "../services/api";
import AppShell from "../components/AppShell";

export default function AdminDashboard(){
 const [responses,setResponses]=useState([]),[forms,setForms]=useState([]),[error,setError]=useState("");
 useEffect(()=>{Promise.all([apiRequest("/forms"),apiRequest("/feedback")]).then(([a,b])=>{setForms(a.forms||[]);setResponses(b.responses||[])}).catch(e=>setError(e.message))},[]);
 const ratings=responses.flatMap(r=>Object.values(r.answers||{}).filter(v=>typeof v==="number"&&v>=1&&v<=5));
 const avg=ratings.length?(ratings.reduce((a,b)=>a+b,0)/ratings.length).toFixed(1):"—";
 const positive=ratings.length?Math.round((ratings.filter(x=>x>=4).length/ratings.length)*100):0;
 return <AppShell title="Admin Dashboard" admin><div className="mx-auto max-w-7xl">
  <div className="mb-6"><p className="text-sm font-semibold text-slate-400">Administration</p><h1 className="mt-1 text-2xl font-extrabold sm:text-3xl">Dashboard Overview</h1><p className="mt-1 text-sm text-slate-500">Monitor and analyze feedback from your workspace.</p></div>
  {error&&<div className="mb-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["▣","Total Feedback",responses.length],["★","Average Rating",avg+"/5"],["✓","Positive Feedback",positive+"%"],["♙","Active Forms",forms.filter(f=>f.isActive).length]].map(([icon,l,v],i)=><article key={l} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-50 text-indigo-600">{icon}</div><p className="mt-3 text-xs text-slate-500">{l}</p><p className="mt-1 text-2xl font-extrabold">{v}</p><p className="mt-1 text-[10px] text-emerald-600">↑ Live activity</p></article>)}</div>
  <div className="mt-5 grid gap-5 lg:grid-cols-[1.35fr_1fr]">
   <section className="rounded-2xl border bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-extrabold">Feedback Trend</h2><p className="mt-1 text-xs text-slate-400">Recent response volume</p></div><button onClick={()=>window.location.href="/analytics"} className="text-xs font-bold text-indigo-600">Analytics →</button></div><div className="mt-6 flex h-52 items-end gap-2 sm:gap-3">{[18,35,28,48,42,62,55,76,68,90].map((v,i)=><div key={i} className="flex flex-1 items-end"><div className="w-full rounded-t-md bg-gradient-to-t from-indigo-500 to-violet-400" style={{height:v+"%"}}/></div>)}</div><div className="mt-2 flex justify-between text-[10px] text-slate-400"><span>Jan</span><span>Mar</span><span>May</span><span>Jul</span><span>Sep</span><span>Oct</span></div></section>
   <section className="rounded-2xl border bg-white p-5 shadow-sm sm:p-6"><h2 className="font-extrabold">Sentiment Snapshot</h2><div className="mt-5 space-y-4">{[["Positive",positive,"bg-emerald-400"],["Neutral",Math.max(0,100-positive-7),"bg-amber-400"],["Needs attention",7,"bg-rose-400"]].map(([l,v,c])=><div key={l}><div className="mb-1 flex justify-between text-xs"><span className="font-semibold text-slate-600">{l}</span><b>{v}%</b></div><div className="h-2 rounded-full bg-slate-100"><div className={"h-full rounded-full "+c} style={{width:v+"%"}}/></div></div>)}</div></section>
  </div>
  <section className="mt-5 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between p-5"><div><h2 className="font-extrabold">Recent Feedback</h2><p className="mt-1 text-xs text-slate-400">Latest submissions</p></div><button onClick={()=>window.location.href="/responses"} className="text-xs font-bold text-indigo-600">View All →</button></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="bg-slate-50 text-slate-400"><tr><th className="px-5 py-3">Student</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">Rating</th><th className="px-5 py-3">Date</th><th className="px-5 py-3 text-right">Status</th></tr></thead><tbody>{responses.slice(0,8).map((r,i)=><tr key={r._id||i} className="border-t border-slate-100"><td className="px-5 py-3 font-bold text-slate-700">{r.submittedBy?.name||"Student"}</td><td className="px-5 py-3 text-slate-500">{r.form?.title||"Course"}</td><td className="px-5 py-3 text-amber-500">★★★★★</td><td className="px-5 py-3 text-slate-500">{new Date(r.createdAt).toLocaleDateString()}</td><td className="px-5 py-3 text-right"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold text-emerald-700">Published</span></td></tr>)}{!responses.length&&<tr><td colSpan="5" className="py-10 text-center text-slate-400">No feedback yet.</td></tr>}</tbody></table></div></section>
 </div></AppShell>;
}