import { useEffect, useMemo, useState } from "react";
import { apiRequest } from "../services/api";
import AppShell from "../components/AppShell";

export default function AdminDashboard() {
  const [responses,setResponses]=useState([]),[forms,setForms]=useState([]),[error,setError]=useState("");
  useEffect(()=>{Promise.all([apiRequest("/forms"),apiRequest("/feedback")]).then(([a,b])=>{setForms(a.forms||[]);setResponses(b.responses||[])}).catch(e=>setError(e.message))},[]);
  const ratings=responses.flatMap(r=>Object.values(r.answers||{}).filter(v=>typeof v==="number"&&v>=1&&v<=5));
  const avg=ratings.length?(ratings.reduce((a,b)=>a+b,0)/ratings.length).toFixed(1):"—";
  const positive=ratings.length?Math.round(ratings.filter(x=>x>=4).length/ratings.length*100):0;
  const active=forms.filter(f=>f.isActive).length;
  const byForm=useMemo(()=>forms.map(f=>({title:f.title,responses:responses.filter(r=>String(r.form?._id||r.form)===String(f._id)).length})).sort((a,b)=>b.responses-a.responses).slice(0,8),[forms,responses]);
  const max=Math.max(...byForm.map(x=>x.responses),1);

  return <AppShell title="Admin Overview" admin><div className="mx-auto max-w-[1400px]">
    <div className="mb-7"><p className="text-xs font-semibold text-slate-400">Administration</p><h2 className="mt-1 text-[30px] font-extrabold tracking-[-0.03em]">Workspace overview</h2><p className="mt-1 text-sm text-slate-500">Monitor forms, response volume and feedback quality.</p></div>
    {error&&<div className="mb-5 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-xs font-semibold text-rose-700">{error}</div>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      {[["Total responses",responses.length,"All submitted feedback"],["Average rating",avg==="—"?"—":avg+"/5","Across rating answers"],["Positive share",positive+"%","Ratings of 4 or 5"],["Active forms",active,"Currently published"]].map(([l,v,d])=><article key={l} className="rounded-xl border border-slate-200 bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,.04)]"><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">{l}</p><p className="mt-2 text-[28px] font-extrabold tracking-tight">{v}</p><p className="mt-1 text-xs text-slate-500">{d}</p></article>)}
    </section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
      <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h3 className="text-sm font-bold">Responses by form</h3><p className="mt-1 text-xs text-slate-400">Live response counts</p></div><button onClick={()=>window.location.href="/analytics"} className="text-xs font-bold text-slate-700 hover:underline">Analytics</button></div>
        <div className="mt-7 space-y-4">{byForm.map((f,i)=><div key={f.title+i}><div className="mb-1.5 flex justify-between gap-4 text-xs"><span className="truncate font-semibold text-slate-700">{f.title}</span><b>{f.responses}</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-900 transition-all" style={{width:Math.max(f.responses?5:0,f.responses/max*100)+"%"}}/></div></div>)}{!byForm.length&&<div className="py-10 text-center text-sm text-slate-400">No form responses yet.</div>}</div>
      </article>
      <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h3 className="text-sm font-bold">Feedback quality</h3><p className="mt-1 text-xs text-slate-400">Based on available ratings</p><div className="mt-8 text-center"><div className="mx-auto grid h-32 w-32 place-items-center rounded-full border-[12px] border-slate-100"><div><p className="text-2xl font-extrabold">{positive}%</p><p className="text-[9px] font-bold uppercase tracking-wide text-slate-400">positive</p></div></div></div><div className="mt-7 grid grid-cols-2 gap-2"><button onClick={()=>window.location.href="/responses"} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold hover:bg-slate-50">Feedbacks</button><button onClick={()=>window.location.href="/forms"} className="rounded-lg bg-slate-950 px-3 py-2 text-xs font-bold text-white hover:bg-slate-800">Manage forms</button></div></article>
    </section>
    <section className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between p-5 sm:p-6"><div><h3 className="text-sm font-bold">Recent feedback</h3><p className="mt-1 text-xs text-slate-400">Latest submissions</p></div><button onClick={()=>window.location.href="/responses"} className="text-xs font-bold text-slate-700 hover:underline">View all</button></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="border-y border-slate-100 bg-slate-50/70 text-slate-400"><tr><th className="px-5 py-3 font-semibold">Form</th><th className="px-5 py-3 font-semibold">Answers</th><th className="px-5 py-3 font-semibold">Submitted</th><th className="px-5 py-3 text-right font-semibold">Status</th></tr></thead><tbody>{responses.slice(0,8).map((r,i)=><tr key={r._id||i} className="border-b border-slate-100 last:border-0"><td className="px-5 py-3 font-semibold text-slate-700">{r.form?.title||"Feedback form"}</td><td className="px-5 py-3 text-slate-500">{Object.keys(r.answers||{}).length} answers</td><td className="px-5 py-3 text-slate-500">{new Date(r.createdAt).toLocaleDateString()}</td><td className="px-5 py-3 text-right"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600">Submitted</span></td></tr>)}{!responses.length&&<tr><td colSpan="4" className="py-10 text-center text-slate-400">No feedback yet.</td></tr>}</tbody></table></div></section>
  </div></AppShell>;
}