import { useEffect,useState } from "react";
import { apiRequest } from "../services/api";
import AppShell from "../components/AppShell";
const bars=["bg-slate-900","bg-slate-700","bg-slate-500","bg-slate-300"];
export default function Analytics(){
 const [data,setData]=useState(null),[error,setError]=useState("");
 useEffect(()=>{apiRequest("/analytics").then(r=>setData(r.analytics)).catch(e=>setError(e.message))},[]);
 const a=data||{totalForms:0,totalResponses:0,averageRating:null,satisfaction:null,byForm:[]}; const max=Math.max(...(a.byForm||[]).map(x=>x.responses||0),1);
 return <AppShell title="Analytics"><div className="mx-auto max-w-7xl"><div className="mb-7"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-slate-400">Insights</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight sm:text-3xl">Analytics</h1><p className="mt-1 text-sm text-slate-500">A clear view of response volume and rating quality.</p></div>{error&&<div className="mb-5 rounded-xl border border-rose-100 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Forms",a.totalForms],["Responses",a.totalResponses],["Average rating",a.averageRating??"—"],["Satisfaction",a.satisfaction==null?"—":a.satisfaction+"%"]].map(([l,v])=><article key={l} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-slate-500">{l}</p><p className="mt-2 text-2xl font-extrabold tracking-tight">{v}</p><p className="mt-1 text-[10px] font-semibold text-slate-400">Current workspace data</p></article>)}</div>
 <div className="mt-5 grid gap-5 lg:grid-cols-[1.45fr_.8fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><h2 className="font-extrabold">Responses by form</h2><span className="text-[10px] text-slate-400">Volume</span></div><div className="mt-7 space-y-5">{a.byForm?.map((f,i)=><div key={f.formId||i}><div className="mb-2 flex justify-between gap-3 text-xs"><span className="truncate font-semibold text-slate-700">{f.title}</span><b className="text-slate-900">{f.responses}</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={"h-full rounded-full "+bars[i%bars.length]} style={{width:Math.max(5,(f.responses/max)*100)+"%"}}/></div></div>)}{!a.byForm?.length&&<p className="py-12 text-center text-sm text-slate-400">No response data yet.</p>}</div></section>
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="font-extrabold">Satisfaction</h2><div className="mx-auto mt-8 grid h-44 w-44 place-items-center rounded-full border-[18px] border-slate-100"><div className="text-center"><p className="text-3xl font-extrabold">{a.satisfaction==null?"—":a.satisfaction+"%"}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-wider text-slate-400">Satisfied</p></div></div><p className="mt-6 text-center text-xs leading-5 text-slate-500">Based on submitted 1–5 ratings. Ratings of 4 or 5 count as satisfied.</p></section></div></div></AppShell>
}