import { useState } from "react";
import { apiRequest } from "../services/api";
import AppShell from "../components/AppShell";
const types=[["rating","Rating · 1–5"],["short","Short answer"],["long","Long answer"],["multiple-choice","Multiple choice"],["yes-no","Yes / No"]];
const empty=()=>({text:"",type:"rating",required:true,options:[]});
export default function CreateForm(){
 const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[questions,setQuestions]=useState([empty()]),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 const update=(i,p)=>setQuestions(q=>q.map((x,n)=>n===i?{...x,...p}:x));
 const submit=async e=>{e.preventDefault();setMessage("");if(!questions.every(q=>q.text.trim()))return setMessage("Every question needs text.");if(questions.some(q=>q.type==="multiple-choice"&&q.options.length<2))return setMessage("Multiple-choice questions need at least two options.");setSaving(true);try{await apiRequest("/forms",{method:"POST",body:JSON.stringify({title:title.trim(),description:description.trim(),questions})});setMessage("Form created. It is now available in My Forms.");setTitle("");setDescription("");setQuestions([empty()])}catch(err){setMessage(err.message)}finally{setSaving(false)}};
 return <AppShell title="Create Form"><div className="mx-auto max-w-4xl"><div className="mb-7"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-slate-400">Form builder</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight sm:text-3xl">Create a feedback form</h1><p className="mt-1 text-sm text-slate-500">Keep questions focused so responses are easy to understand and analyze.</p></div>
 <form onSubmit={submit} className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-extrabold">Form details</h2><p className="mt-1 text-xs text-slate-400">Give respondents enough context before they begin.</p></div><span className="text-xs font-bold text-slate-400">{questions.length} question{questions.length!==1?"s":""}</span></div><div className="mt-5 space-y-3"><input className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none transition focus:border-slate-900 focus:ring-2 focus:ring-slate-100" placeholder="e.g. Course feedback · October 2026" value={title} onChange={e=>setTitle(e.target.value)} required/><textarea className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none transition focus:border-slate-900 focus:ring-2 focus:ring-slate-100" placeholder="Short description for respondents" value={description} onChange={e=>setDescription(e.target.value)} rows="3"/></div></section>
 {questions.map((q,i)=><section key={i} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Question {String(i+1).padStart(2,"0")}</span>{questions.length>1&&<button type="button" onClick={()=>setQuestions(x=>x.filter((_,n)=>n!==i))} className="text-xs font-bold text-rose-600">Remove</button>}</div><input className="mt-4 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-slate-900" placeholder="What do you want to learn?" value={q.text} onChange={e=>update(i,{text:e.target.value})} required/><div className="mt-3 grid gap-3 sm:grid-cols-[1fr_auto]"><select className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm" value={q.type} onChange={e=>update(i,{type:e.target.value,options:[]})}>{types.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><label className="flex items-center gap-2 rounded-xl border border-slate-200 px-4 text-xs font-bold text-slate-600"><input type="checkbox" checked={q.required} onChange={e=>update(i,{required:e.target.checked})} className="accent-slate-900"/> Required</label></div>{q.type==="multiple-choice"&&<input className="mt-3 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm" placeholder="Option 1, Option 2, Option 3" value={q.options.join(", ")} onChange={e=>update(i,{options:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/>}</section>)}
 <button type="button" onClick={()=>setQuestions(q=>[...q,{...empty(),type:"short",required:false}])} className="w-full rounded-xl border border-dashed border-slate-300 bg-white py-3 text-sm font-bold text-slate-600 hover:border-slate-500 hover:text-slate-900">+ Add question</button>
 {message&&<div className={"rounded-xl border p-3 text-sm "+(message.startsWith("Form created")?"border-emerald-100 bg-emerald-50 text-emerald-700":"border-rose-100 bg-rose-50 text-rose-700")}>{message}</div>}
 <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={()=>window.location.href="/forms"} className="rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold text-slate-600">Cancel</button><button disabled={saving} className="rounded-xl bg-slate-950 px-6 py-3 text-sm font-bold text-white disabled:opacity-50">{saving?"Creating…":"Create form →"}</button></div>
 </form></div></AppShell>
}