import { useEffect, useState } from "react";
import { apiRequest } from "../services/api";
import AppShell from "../components/AppShell";

export default function MyForms() {
  const [forms,setForms]=useState([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
  const load=async()=>{try{const d=await apiRequest("/forms/mine");setForms(d.forms||[])}catch(e){setMessage(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const toggle=async f=>{try{await apiRequest("/forms/"+f._id,{method:"PUT",body:JSON.stringify({isActive:!f.isActive})});setForms(x=>x.map(v=>v._id===f._id?{...v,isActive:!v.isActive}:v))}catch(e){setMessage(e.message)}};
  const remove=async id=>{if(!window.confirm("Delete this feedback form?"))return;try{await apiRequest("/forms/"+id,{method:"DELETE"});setForms(x=>x.filter(v=>v._id!==id))}catch(e){setMessage(e.message)}};
  return <AppShell title="My Feedback Forms"><div className="mx-auto max-w-7xl">
    <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-slate-400">Forms</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight sm:text-3xl">Feedback forms</h1><p className="mt-1 text-sm text-slate-500">Build, publish and maintain the forms owned by your workspace.</p></div><button onClick={()=>window.location.href="/forms/new"} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white shadow-sm hover:bg-slate-800">Create form <span className="ml-1">→</span></button></div>
    {message&&<div className="mb-5 rounded-xl border border-rose-100 bg-rose-50 p-3 text-sm text-rose-700">{message}</div>}
    {loading?<div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-400">Loading your forms…</div>:!forms.length?<div className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-slate-950 text-white font-black">F</div><h2 className="mt-4 font-extrabold">Your workspace is ready</h2><p className="mx-auto mt-1 max-w-md text-sm text-slate-500">Create your first form to start collecting structured feedback and measuring responses.</p><button onClick={()=>window.location.href="/forms/new"} className="mt-5 rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-bold text-white">Create first form</button></div>:
    <div className="grid gap-4 lg:grid-cols-2">{forms.map(f=><article key={f._id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-slate-300">
      <div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate font-extrabold text-slate-900">{f.title}</h2><span className={"rounded-full px-2 py-1 text-[10px] font-bold "+(f.isActive?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500")}>{f.isActive?"Live":"Paused"}</span></div><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{f.description||"No description provided."}</p></div><span className="shrink-0 rounded-lg border border-slate-200 px-2.5 py-1.5 text-[10px] font-bold text-slate-500">{f.questions?.length||0} questions</span></div>
      <div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-[11px] text-slate-400">Created {f.createdAt?new Date(f.createdAt).toLocaleDateString():"—"}</span><div className="flex gap-2"><button onClick={()=>toggle(f)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700 hover:bg-slate-50">{f.isActive?"Pause":"Publish"}</button><button onClick={()=>remove(f._id)} className="rounded-lg border border-rose-100 px-3 py-2 text-xs font-bold text-rose-600 hover:bg-rose-50">Delete</button></div></div>
    </article>)}</div>}
  </div></AppShell>
}