import { useEffect,useState } from "react";
import { apiRequest } from "../services/api";
import AppShell from "../components/AppShell";

export default function MyForms(){
 const [forms,setForms]=useState([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const load=async()=>{try{const d=await apiRequest("/forms/mine");setForms(d.forms||[]);}catch(e){setMessage(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const toggle=async f=>{try{await apiRequest("/forms/"+f._id,{method:"PUT",body:JSON.stringify({isActive:!f.isActive})});setForms(x=>x.map(v=>v._id===f._id?{...v,isActive:!v.isActive}:v))}catch(e){setMessage(e.message)}};
 const remove=async id=>{if(!window.confirm("Delete this feedback form?"))return;try{await apiRequest("/forms/"+id,{method:"DELETE"});setForms(x=>x.filter(v=>v._id!==id))}catch(e){setMessage(e.message)}};
 return <AppShell title="My Feedback Forms"><div className="mx-auto max-w-7xl">
  <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-slate-400">Workspace</p><h1 className="mt-1 text-2xl font-extrabold sm:text-3xl">My Feedback Forms</h1><p className="mt-1 text-sm text-slate-500">Create, manage and publish feedback forms.</p></div><button onClick={()=>window.location.href="/forms/new"} className="rounded-xl bg-gradient-to-r from-indigo-600 to-violet-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-indigo-100">+ Create Form</button></div>
  {message&&<div className="mb-4 rounded-xl border border-rose-100 bg-rose-50 p-3 text-sm text-rose-700">{message}</div>}
  {loading?<div className="rounded-2xl border bg-white p-8 text-center text-sm text-slate-400">Loading forms...</div>:!forms.length?<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-indigo-50 text-indigo-600">▧</div><h2 className="mt-4 font-bold">No forms yet</h2><p className="mt-1 text-sm text-slate-500">Create your first feedback form to start collecting responses.</p></div>:
  <div className="grid gap-4 md:grid-cols-2">{forms.map(f=><article key={f._id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-extrabold text-slate-900">{f.title}</h2><span className={"rounded-full px-2 py-1 text-[10px] font-bold "+(f.isActive?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500")}>{f.isActive?"Active":"Inactive"}</span></div><p className="mt-2 text-sm leading-6 text-slate-500">{f.description||"No description provided."}</p></div><span className="rounded-xl bg-indigo-50 px-2.5 py-2 text-xs font-bold text-indigo-600">{f.questions?.length||0} Q</span></div><div className="mt-5 flex flex-wrap gap-2 border-t border-slate-100 pt-4"><button onClick={()=>toggle(f)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700">{f.isActive?"Deactivate":"Activate"}</button><button onClick={()=>remove(f._id)} className="rounded-lg border border-rose-100 px-3 py-2 text-xs font-bold text-rose-600">Delete</button></div></article>)}</div>}
 </div></AppShell>;
}