import { useEffect,useState } from "react";
import { apiRequest } from "../services/api";
import AppShell from "../components/AppShell";
export default function Responses(){
 const [responses,setResponses]=useState([]),[query,setQuery]=useState(""),[error,setError]=useState("");
 useEffect(()=>{apiRequest("/feedback").then(d=>setResponses(d.responses||[])).catch(e=>setError(e.message))},[]);
 const filtered=responses.filter(r=>(r.form?.title||"").toLowerCase().includes(query.toLowerCase()));
 return <AppShell title="My Feedback"><div className="mx-auto max-w-7xl"><div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-slate-400">History</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight sm:text-3xl">My feedback</h1><p className="mt-1 text-sm text-slate-500">A private record of feedback you have submitted.</p></div><input className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-slate-900 sm:w-72" placeholder="Search forms…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
 {error&&<div className="mb-5 rounded-xl border border-rose-100 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
 <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><p className="text-sm font-extrabold">{filtered.length} submission{filtered.length!==1?"s":""}</p><span className="text-[11px] text-slate-400">Newest first</span></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="bg-slate-50 text-slate-400"><tr><th className="px-5 py-3 font-bold">Form</th><th className="px-5 py-3 font-bold">Submitted</th><th className="px-5 py-3 font-bold">Answers</th><th className="px-5 py-3 text-right font-bold">Status</th></tr></thead><tbody>{filtered.map(r=><tr key={r._id} className="border-t border-slate-100 hover:bg-slate-50/60"><td className="px-5 py-4 font-bold text-slate-800">{r.form?.title||"Feedback form"}</td><td className="px-5 py-4 text-slate-500">{r.createdAt?new Date(r.createdAt).toLocaleString(): "—"}</td><td className="px-5 py-4 text-slate-500">{Object.keys(r.answers||{}).length} answer fields</td><td className="px-5 py-4 text-right"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold text-emerald-700">Submitted</span></td></tr>)}{!filtered.length&&<tr><td colSpan="4" className="py-14 text-center"><p className="font-bold text-slate-700">No feedback found</p><p className="mt-1 text-xs text-slate-400">Your submitted responses will appear here.</p></td></tr>}</tbody></table></div></div></div></AppShell>
}