import { useEffect,useState } from "react";
import { apiRequest } from "../services/api";
import AppShell from "../components/AppShell";
export default function SubmitFeedback(){
 const [forms,setForms]=useState([]),[selected,setSelected]=useState(""),[answers,setAnswers]=useState([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 useEffect(()=>{apiRequest("/forms").then(d=>setForms((d.forms||[]).filter(f=>f.isActive!==false))).catch(e=>setMessage(e.message)).finally(()=>setLoading(false))},[]);
 const choose=id=>{setSelected(id);const f=forms.find(x=>x._id===id);setAnswers((f?.questions||[]).map(()=> ""));setMessage("")};
 const update=(i,v)=>setAnswers(a=>a.map((x,n)=>n===i?v:x));
 const submit=async e=>{e.preventDefault();const f=forms.find(x=>x._id===selected);if(!f)return setMessage("Select a feedback form.");if(f.questions.some((q,i)=>q.required&&(answers[i]===undefined||answers[i]==="")))return setMessage("Please answer all required questions.");setSaving(true);setMessage("");try{await apiRequest("/feedback",{method:"POST",body:JSON.stringify({formId:selected,answers})});setMessage("Feedback submitted successfully.");setSelected("");setAnswers([])}catch(err){setMessage(err.message)}finally{setSaving(false)}};
 const form=forms.find(f=>f._id===selected);
 return <AppShell title="Give Feedback"><div className="mx-auto max-w-4xl"><div className="mb-7"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-slate-400">Response</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight sm:text-3xl">Give feedback</h1><p className="mt-1 text-sm text-slate-500">Share a thoughtful response. Required questions are marked with an asterisk.</p></div>
 <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-extrabold">Choose a form</h2><p className="mt-1 text-xs text-slate-400">Only active forms are shown.</p></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-[10px] font-bold text-slate-500">{form?form.questions.length+" questions":"Step 1"}</span></div><div className="mt-4"><select required disabled={loading} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-slate-900" value={selected} onChange={e=>choose(e.target.value)}><option value="">{loading?"Loading forms…":"Choose a feedback form"}</option>{forms.map(f=><option key={f._id} value={f._id}>{f.title}</option>)}</select></div></div>
 {form&&<div className="p-5 sm:p-7"><div className="mb-6 rounded-xl bg-slate-50 p-4"><p className="font-bold text-slate-800">{form.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{form.description||"Please answer each question as accurately as possible."}</p></div><div className="space-y-7">{form.questions.map((q,i)=><div key={q._id||i}><label className="mb-3 block text-sm font-bold text-slate-800">{i+1}. {q.text}{q.required&&<span className="text-rose-500"> *</span>}</label>
 {q.type==="rating"?<div className="flex gap-2">{[1,2,3,4,5].map(n=><button type="button" key={n} aria-label={"Rating "+n} onClick={()=>update(i,n)} className={"grid h-11 w-11 place-items-center rounded-xl border text-sm font-bold "+(answers[i]===n?"border-slate-950 bg-slate-950 text-white":"border-slate-200 text-slate-500 hover:border-slate-400")}>{n}</button>)}</div>:
 q.type==="long"||q.type==="textarea"?<textarea required={q.required} className="min-h-32 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-slate-900" placeholder="Write your response…" value={answers[i]||""} onChange={e=>update(i,e.target.value)}/>:
 q.type==="yes-no"?<div className="flex gap-2">{["Yes","No"].map(v=><button type="button" key={v} onClick={()=>update(i,v)} className={"rounded-xl border px-5 py-2.5 text-sm font-bold "+(answers[i]===v?"border-slate-950 bg-slate-950 text-white":"border-slate-200 text-slate-600 hover:bg-slate-50")}>{v}</button>)}</div>:
 q.type==="multiple-choice"?<select required={q.required} className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm" value={answers[i]||""} onChange={e=>update(i,e.target.value)}><option value="">Select an option</option>{(q.options||[]).map(o=><option key={o}>{o}</option>)}</select>:
 <input required={q.required} className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-slate-900" placeholder="Type your answer…" value={answers[i]||""} onChange={e=>update(i,e.target.value)}/>}</div>)}</div></div>}
 {message&&<div className={"mx-5 mb-5 rounded-xl border p-3 text-sm sm:mx-7 "+(message.includes("successfully")?"border-emerald-100 bg-emerald-50 text-emerald-700":"border-rose-100 bg-rose-50 text-rose-700")}>{message}</div>}
 {selected&&<div className="flex justify-end border-t border-slate-100 p-5 sm:p-6"><button disabled={saving} className="rounded-xl bg-slate-950 px-6 py-3 text-sm font-bold text-white disabled:opacity-50">{saving?"Submitting…":"Submit feedback →"}</button></div>}
 </form></div></AppShell>
}